import type { DashboardData } from "@/lib/types";

export const dashboardData = {
  meta: {
    dataRange: "Naver DataLab 연결 중",
    lastUpdated: "-",
    comparisonLabel: "전주 대비 증감률",
    apiSource: "local_fallback",
  },
  page1Summary: {
    analyzedProducts: 0,
    analyzedIngredients: 0,
    totalSearchGrowthRate: 0,
    risingIngredientCount: 0,
    supplyShortageIngredientCount: 0,
  },
  page1: {
    functionRisers: [],
    functionDemand: [],
    ingredientPopularity: [],
    ingredientDemand: [],
    priceDistribution: [],
    demandSupplyMatrix: [],
    insights: [],
  },
  page2: {
    periodLabel: "스냅샷",
    selectedIngredient: "나이아신아마이드",
    selectedSummary: {
      growthRate: 0,
      startIndex: 0,
      endIndex: 0,
      periodKey: "snapshot",
      ingredientSet: "main",
    },
    searchTrend: {
      dates: [],
      series: [],
    },
    concernMetrics: [
      { key: "wrinkleElasticity", label: "주름/탄력" },
      { key: "toneSpot", label: "잡티/톤" },
      { key: "troubleCalming", label: "트러블/진정" },
      { key: "drynessBarrier", label: "건조/장벽" },
      { key: "poreSebum", label: "모공/피지" },
    ],
    marketProducts: [],
    concernTable: [],
    ageTopIngredients: [],
    insights: [],
  },
  page3: {},
  page4: {
    alertDate: "",
    summary: {
      opportunityCount: 0,
      inventoryRiskCount: 0,
      reviewIssueCount: 0,
    },
    alerts: [],
  },
  page5: {
    promptPlaceholder: "예: 건성 타겟을 위한 레티놀 마케팅 전략 제안해줘",
    suggestions: [
      "이번 주 진입 검토 성분 추천해줘",
      "건성 타겟 레티놀 전략 알려줘",
      "공급 과열 성분 알려줘",
      "부정 리뷰 많은 성분 개선 방향 알려줘",
      "20대 타겟 미백 성분 전략 제안해줘",
    ],
    insights: [
      {
        id: "dry-retinol",
        title: "건성 타겟 레티놀 번들 전략",
        level: "높음",
        summary: "검색 수요는 상승 중이지만 건성 리뷰에서 건조감 이슈가 함께 증가했습니다.",
        evidence: "레티놀 검색 수요 상승과 건성 리뷰 건조감 이슈를 함께 고려한 기본 추천입니다.",
        strategy: "레티놀 + 세라마이드/판테놀 보습 조합을 묶고, 첫 2주 사용 루틴을 상세페이지 상단에 배치하세요.",
        issues: ["건조감", "자극", "따가움"],
        directions: ["세라마이드/판테놀 결합", "저자극 메시지", "샘플링 유도"],
        actions: ["상세페이지 문구 개선", "리뷰 키워드 반영", "배너 카피 제안"],
        detailSections: [
          {
            title: "검토 포인트",
            items: ["3페이지 리뷰 분석에서 건성 부정 키워드를 확인합니다.", "1페이지 가격 분포를 함께 보고 번들 가격대를 정합니다."],
          },
        ],
      },
      {
        id: "pdrn-content",
        title: "PDRN 비교 콘텐츠 테스트",
        level: "중간",
        summary: "PDRN은 수요 대비 공급 노출이 낮아 콘텐츠 선점 여지가 있습니다.",
        evidence: "수요-공급 매트릭스와 검색 트렌드를 함께 보는 기본 추천입니다.",
        strategy: "레티놀 대비 회복/광채 포지션을 강조한 숏폼 A/B 테스트를 7일 단위로 운영하세요.",
        issues: ["콘텐츠 선점 필요"],
        directions: ["회복/광채 포지션 강조", "성분 비교 콘텐츠 발행"],
        actions: ["숏폼 소재 제작", "키워드 광고 테스트"],
      },
      {
        id: "adenosine-check",
        title: "아데노신 프로모션 효율 점검",
        level: "중간",
        summary: "공급 노출은 높지만 검색 수요가 약해 발주 확대 전 검토가 필요합니다.",
        evidence: "공급 과잉 가능성이 있는 성분은 발주보다 재고 회전율을 먼저 확인합니다.",
        strategy: "신규 발주 확대보다 기존 SKU의 가격/증정 혜택 반응과 리뷰 키워드를 먼저 확인하세요.",
        issues: ["공급 과잉", "수요 둔화"],
        directions: ["재고 회전율 점검", "증정 혜택 반응 확인"],
        actions: ["기획전 효율 검토", "발주 확대 보류"],
      },
    ],
    targetStrategy: {
      title: "레티놀 × 건성 타겟 전략",
      issues: ["건조감", "자극", "따가움"],
      directions: ["세라마이드/판테놀 결합", "저자극 메시지", "샘플링 유도"],
      actions: ["상세페이지 문구 개선", "리뷰 키워드 반영", "배너 카피 제안"],
    },
  },
} satisfies DashboardData;
